### ISSUE TITLE
 padding y margin 0%

### ISSUE THREAD

**Issue by hackchele** [JuanMorales10/Mercado-Liebre#1]
agregar el padding y margin en el css 
*{
    box-sizing: border-box;
    margin:0% 0% 0% 0%;
    padding:0% 0% 0% 0%;
}

**Comment by LovelyDev829** [comment]
The CSS code you provided will set the box-sizing property to border-box for all elements, and set the margin and padding to 0% for all sides of all elements. However, the percentage values you used are not necessary for the margin and padding properties. It's generally more common to use pixel (px), em (em), or rem (rem) values for margins and paddings.

If you want to set specific values for the margin and padding properties, you can modify the code as follows:

`* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}`

In this updated code, the margin and padding properties are set to 0 for all sides of all elements. If you want to add specific values for margin and padding, you can replace the 0 with the desired value using appropriate units. For example:

`* {
    box-sizing: border-box;
    margin: 10px;
    padding: 20px;
}`

In this case, all elements will have a margin of 10 pixels and padding of 20 pixels on all sides.

Remember to include this CSS code within <style> tags in your HTML document or in a separate CSS file and link it to your HTML file.

Let me know if you need further assistance!
